# Generated by Django 5.0.1 on 2024-01-07 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_appointment_therapistprofile_transcript'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='realID',
        ),
        migrations.RemoveField(
            model_name='therapistprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='therapistprofile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='patient',
            name='therapist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.therapistprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
