# Generated by Django 5.0.1 on 2024-01-15 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_appointment_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='location',
        ),
    ]
