# Generated by Django 5.0.1 on 2024-01-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_appointment_is_active_appointment_canceled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='canceled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
