# Generated by Django 5.0.1 on 2024-01-25 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_appointmentdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppointmentDetail',
        ),
    ]
