# Generated by Django 5.0.1 on 2024-01-25 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_appointmentdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='base.appointmentdetail'),
            preserve_default=False,
        ),
    ]
