# Generated by Django 5.0.1 on 2024-01-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_appointment_appointment_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_detail',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='canceled',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='cancellation_reason',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='price',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='recurring_frequency',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='time_of_day',
        ),
       migrations.AddField(
    model_name='appointment',
    name='occurrence_date',
    field=models.DateField(default='2024-01-25'),  # Set a valid default date
    preserve_default=False,
),
        migrations.AddField(
            model_name='patient',
            name='canceled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='day_of_week',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='recurring_frequency',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
       migrations.AddField(
    model_name='patient',
    name='time_of_day',
    field=models.TimeField(default='12:00:00'),  # Set a valid default time
    preserve_default=False,
),

        migrations.DeleteModel(
            name='AppointmentDetail',
        ),
    ]
