# Generated by Django 5.0.1 on 2024-01-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_appointment_appointment_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='time_of_day',
            field=models.TimeField(default='12:00:00'),
        ),
    ]
