# Generated by Django 5.0.1 on 2024-01-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_patient_time_of_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='recurring_frequency',
            field=models.CharField(blank=True, default='Weekly', max_length=50, null=True),
        ),
    ]
