# Generated by Django 5.0.1 on 2024-01-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_patient_recurring_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='occurrence_date',
            field=models.DateField(default='YYYY-MM-DD'),
        ),
    ]
