# Generated by Django 5.0.1 on 2024-01-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_appointment_occurrence_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='time_of_day',
            field=models.TimeField(),
        ),
    ]
