# Generated by Django 5.0.1 on 2024-01-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_patient_time_of_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='occurrence_date',
            field=models.DateField(default='2024-01-25'),
        ),
    ]
