# Generated by Django 5.0.1 on 2024-01-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_appointment_occurrence_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='time_of_day',
        ),
        migrations.AddField(
            model_name='appointment',
            name='time_of_day',
            field=models.TimeField(default='12:00:00'),
            preserve_default=False,
        ),
    ]
